### ISSUE TITLE
Example with twig

### ISSUE THREAD

**Issue by javipuche** [jabney/render-template-loader-demo#1]
Can do you do a example with twig please.

Thanks

**Comment by jabney** [comment]
Hi Javier,

Start [here](https://github.com/jabney/render-template-loader/blob/master/test/twig.spec.js) with the [unit test for `twig`](https://github.com/jabney/render-template-loader/blob/master/test/twig.spec.js):

```javascript
import compiler from './compiler.js'
import helpers from './helpers'

test('Renders a Twig template', async () => {
  const options = {
    engine: 'twig',
    locals: {
      title: 'Twig Template',
      desc: 'A template rendered by Twig'
    }
  }

  const stats = await compiler('data/source.twig', options)
  const output = stats.toJson().modules[0].source
  const source = helpers.value(output)

  expect(source).toContain('<h1>Twig Template</h1>')
  expect(source).toContain('<h2>A template rendered by Twig</h2>')
})
```

Here's what the [source](https://github.com/jabney/render-template-loader/blob/master/test/data/source.twig) for that test looks like:

```html
<h1>{{ title }}</h1>
<h2>{{ desc }}</h2>
```

Output:
```html
<h1>Twig Template</h1>
<h2>A template rendered by Twig</h2>
```

The `options` constant in the above test defines that part of the webpack configuration for `render-template-loader`. 

For example, the `render-template-loader` options below is the same as the above test `options` constant.

**webpack.config.js**

```javascript
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  entry: './src/index.js',
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    rules: [{
      test: /\/src\/index.twig$/,
      use: [{
        loader: 'render-template-loader',
        options: {
          engine: 'twig',
          locals: {
            title: 'Twig Template',
            desc: 'A template rendered by Twig'
          }
        }
      }]
    }]
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: 'src/index.twig'
    })
  ]
}
```

So that's basic `twig` support as it works in the unit tests. Because the test reflects a basic level of support, I can't be certain it will work if you're doing any sort of advanced twig-fu.

See [these tests](https://github.com/jabney/render-template-loader/blob/master/test/loader.spec.js) for examples of setting up a custom loader options configuration if you need a bit more flexibility.

Best,
James

P.S. I'll add this example to the demo project config when I have a chance!

**Comment by javipuche** [comment]
Thanks you!
